# Generated by Django 3.2.12 on 2022-04-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='plans',
            field=models.ManyToManyField(related_name='records', to='cashapp.Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='cashapp.account'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
