# Generated by Django 3.2.12 on 2022-04-17 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0006_alter_account_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 17, 16, 18, 24, 206733), null=True),
        ),
    ]
