# Generated by Django 3.2.12 on 2022-04-17 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0007_record_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 17, 8, 20, 23, 86706), null=True),
        ),
    ]
