# Generated by Django 3.2.12 on 2022-04-17 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0008_alter_record_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 17, 17, 10, 31, 292190), null=True),
        ),
    ]
