# Generated by Django 3.2.12 on 2022-04-18 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0010_alter_record_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 18, 9, 53, 21, 319505), null=True),
        ),
    ]
