# Generated by Django 3.2.12 on 2022-04-18 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0011_alter_record_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 13, 23, 35, 751439)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 13, 23, 35, 751439)),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 18, 13, 23, 35, 751439), null=True),
        ),
    ]
