# Generated by Django 3.2.12 on 2022-04-18 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0006_userprofile_avatar_back_up'),
        ('cashapp', '0012_auto_20220418_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 13, 29, 6, 519868)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 13, 29, 6, 519868)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='authsys.userprofile'),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 18, 13, 29, 6, 519868), null=True),
        ),
    ]
