# Generated by Django 3.2.12 on 2022-04-18 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0013_auto_20220418_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 13, 29, 13, 867273)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 13, 29, 13, 867273)),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 18, 13, 29, 13, 867273), null=True),
        ),
    ]
