# Generated by Django 3.2.12 on 2022-04-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0003_auto_20220414_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default_img.png', upload_to=''),
        ),
    ]
