# Generated by Django 3.2.12 on 2022-04-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
