# Generated by Django 3.2.12 on 2022-04-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0005_auto_20220416_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_back_up',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
